######################### Ground_filter ###################### not used
do_ground_filtering: true
clip_height: 0.4
sensor_height: 1.5
min_distance: 2.0
max_distance: 75.0
num_iter: 10
num_lpr: 20
th_seeds: 1.2
th_dist: 0.3

######################### Submap_genrator ######################
# seqs: [urban00,urban01,urban02,urban03,urban04,urban05,urban07,urban08,urban09,urban10,urban12,urban13,urban14,urban15,urban16,urban17]
seqs: [urban11] 
seq_data_root: /home/yyj/dl_dataset/kaist/
submap_frame_num: 50 #调用最新关键帧的前多少帧组成submap
submap_cube_size: 50 # submap cube的 完整边长  not used 
submap_gap: 10
submap_point_num: 10000





